### PR TITLE
Add secrets for system tests.

### PR DESCRIPTION
**Pull request by tswast**
Adds `secrets.tar.enc` which contains an API key, so that CircleCI can run
the integration tests. Secret for the tar is configured in the web UI.

Increases the timeout to help with potential flakiness.
http://stackoverflow.com/a/23492442/101923
https://github.com/karma-runner/karma/issues/598

### CODE REVIEW

**Comment by tswast** [comment]
Build failure looks like it is due to bad untar. I need to tar with GNU tar instead of BSD tar from Mac. http://superuser.com/a/318810/125262

**Comment by tswast** [comment]
Well, it finally worked. I think it wasn't Travis's fault, just a busted encryption.

**Comment by tswast** [comment]
I added a commit to switch back to Travis. I was able to use the "SSH debug" feature of Circle CI to figure out that my original problem in #2 was that I was messing up the encryption/decryption steps.

**Comment by tswast** [comment]
I guess I should close this?

**Comment by gguuss** [comment]
If the tests are green again, no sense in re-adding.

**Pull request closed without merging**
